# Generated by Django 5.1.5 on 2025-11-09 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_description', models.TextField(blank=True)),
                ('total_duration_weeks', models.IntegerField()),
                ('recommended_daily_study_time', models.CharField(default='1-2 hours', max_length=50)),
                ('study_plan_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('estimated_hours', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='pdf.studyplan')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('study_plan', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('reading', 'Reading'), ('assignment', 'Assignment'), ('practical', 'Practical Task'), ('project', 'Project'), ('review', 'Review'), ('quiz', 'Quiz'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('study_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pdf.studyweek')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
