# Generated by Django 5.1.5 on 2025-11-13 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_studyplan_studyweek_studyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('handout', 'Handout/Notes'), ('syllabus', 'Syllabus'), ('textbook', 'Textbook'), ('other', 'Other')], default='handout', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='plan_mode',
            field=models.CharField(choices=[('basic', 'Basic Study Plan'), ('enhanced', 'Enhanced with Resources')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='syllabus_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_study_plans', to='pdf.document'),
        ),
        migrations.AlterField(
            model_name='studyactivity',
            name='activity_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('assignment', 'Assignment'), ('practical', 'Practical Task'), ('project', 'Project'), ('review', 'Review'), ('quiz', 'Quiz'), ('video', 'Video Tutorial'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_study_plans', to='pdf.document'),
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('article', 'Article'), ('documentation', 'Documentation'), ('tutorial', 'Tutorial'), ('course', 'Online Course'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('study_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pdf.studyweek')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
