# Generated by Django 5.2.6 on 2025-11-14 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_document_document_type_studyplan_plan_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak Achievement'), ('completion', 'Completion Achievement'), ('speed', 'Speed Achievement'), ('dedication', 'Dedication Achievement'), ('milestone', 'Milestone Achievement')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('icon', models.CharField(default='ri-trophy-line', max_length=50)),
                ('xp_reward', models.IntegerField(default=50)),
                ('criteria', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='learningresource',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('activities_completed', models.IntegerField(default=0)),
                ('videos_watched', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pdf.studyplan')),
                ('study_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.studyweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_study_time_minutes', models.IntegerField(default=0)),
                ('total_activities_completed', models.IntegerField(default=0)),
                ('total_weeks_completed', models.IntegerField(default=0)),
                ('total_videos_watched', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_new', models.BooleanField(default=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
