# Generated by Django 5.2.6 on 2025-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0007_question_answer_quiz_question_quiz_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_quiz_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_quiz_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_perfect_scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_quizzes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_quizzes_passed',
            field=models.IntegerField(default=0),
        ),
    ]
