# Generated by Django 5.1.5 on 2026-03-05 14:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(choices=[('ACTIVITY', 'Complete Activities'), ('QUIZ', 'Answer Quiz Questions'), ('LOGIN', 'Daily Check-in')], max_length=20)),
                ('goal_count', models.IntegerField(default=1)),
                ('reward_xp', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.dailyquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quest', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
