# Generated by Django 5.1.5 on 2026-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_dailyquest_userdailyquest_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='boss_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='boss_sprite',
            field=models.CharField(blank=True, help_text='Sprite identifier (e.g. dragon, hydra)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='boss_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_victory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='player_hp',
            field=models.IntegerField(default=100),
        ),
    ]
